version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:latest

dependencies:
  python_interpreter:
    package_system: python3
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - gcc
    - python3-devel
    - libffi-devel
    - openssl-devel
    - krb5-devel
    - make
    - git
    # - openssh-clients
    # - sshpass
  galaxy:
    collections:
      - name: community.general
