version: 3

images:
  base_image:
    name: quay.io/ansible/awx-ee:24.6.1

dependencies:
  python_interpreter:
    package_system: python3

  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system: []
  python: []
  galaxy:
    roles:
      - name: lablabs.rke2
        src: https://github.com/lablabs/ansible-role-rke2.git
        scm: git
        version: main

    collections:
      - name: community.general
      - name: community.docker
      - name: kubernetes.core

additional_build_files:
  - src: files/ansible.cfg
    dest: configs
